# Constructor for slurm_job class (not exported)
slurm_job <- function(jobname, job_id, nodes) {
    slr_job <- list(jobname = jobname, job_id = job_id, nodes = nodes)
    class(slr_job) <- "slurm_job"
    slr_job
}


#' Cancels a scheduled SLURM job
#'
#' This function cancels the specified SLURM job by invoking the SLURM 
#' \code{scancel} command. It does \emph{not} delete the temporary files 
#' (e.g. scripts) created by \code{\link{slurm_apply}}. 
#' Use \code{\link{cleanup_files}} to remove those files. 
#' 
#' @param slr_job A \code{slurm_job} object output by \code{\link{slurm_apply}}.
#' @seealso \code{\link{slurm_apply}}, \code{\link{cleanup_files}}
#' @export
cancel_slurm <- function(slr_job) {
    if (!(class(slr_job) == "slurm_job")) stop("input must be a slurm_job")
    system(paste("scancel -n", slr_job$jobname))
}


#' Prints the status of a SLURM job and, if completed, its console/error output
#'
#' Prints the status of a SLURM job and, if completed, its console/error output.
#'
#' If the specified SLURM job is still in the queue or running, this function
#' prints its current status (as output by the SLURM \code{squeue} command).
#' The output displays one row by node currently running part of the job ("R" in
#' the "ST" column) and how long it has been running ("TIME"). One row indicates
#' the portions of the job still in queue ("PD" in the "ST" column), if any. 
#' 
#' If all portions of the job have completed or stopped, the function prints the 
#' console and error output, if any, generated by each node.
#' 
#' @param slr_job A \code{slurm_job} object output by \code{\link{slurm_apply}}.
#' @seealso \code{\link{slurm_apply}}
#' @export
print_job_status <- function(slr_job) {
    if (!(class(slr_job) == "slurm_job")) stop("input must be a slurm_job")  
    stat <- suppressWarnings(
        system(paste("squeue -n", slr_job$jobname), intern = TRUE))
    if (length(stat) > 1) {
        print(c("Job running or in queue. Status:", stat))
    } else {
        print("Job completed or stopped. Printing console output below if any.")
        tmpdir <- paste0(".rslurm_", slr_job$jobname)
        out_files <- file.path(tmpdir, 
                               paste0("slurm_", 0:(slr_job$nodes - 1), ".out"))
        slurm_out <- suppressWarnings(
            lapply(out_files, function(x) paste(readLines(x), sep = "\n")))
        for (s in slurm_out) {
            if (length(s) > 0) print(s)
        } 
    }
}  


#' Reads the output of a function calculated on the SLURM cluster 
#'
#' This function reads all function output files (one by cluster node used) from 
#' the specified SLURM job and returns the result in a single data frame
#' (if "table" format selected) or list (if "raw" format selected). It doesn't 
#' record any messages (including warnings or errors) output to the R console
#' during the computation; these can be consulted by invoking 
#' \code{\link{print_job_status}}.
#' 
#' @param slr_job A \code{slurm_job} object output by \code{\link{slurm_apply}}.
#' @param outtype Can be "table" or "raw", see "Value" below for details.
#' @return If \code{outtype = "table"}: A data frame with one column by 
#'   return value of the function passed to \code{slurm_apply}, where 
#'   each row is the output of the corresponding row in the params data frame 
#'   passed to \code{slurm_apply}.
#'   
#'   If \code{outtype = "raw"}: A list where each element is the output 
#'   of the function passed to \code{slurm_apply} for the corresponding
#'   row in the params data frame passed to \code{slurm_apply}.
#' @seealso \code{\link{slurm_apply}}, \code{\link{print_job_status}}
#' @export
get_slurm_out <- function(slr_job, outtype = "raw") {
    if (!(class(slr_job) == "slurm_job")) stop("slr_job must be a slurm_job")
    outtypes <- c("table", "raw")
    if (!(outtype %in% outtypes)) {
        stop(paste("outtype should be one of:", paste(outtypes, collapse = ', ')))
    }
    
    res_files <- paste0("results_", 0:(slr_job$nodes - 1), ".RData")
    tmpdir <- paste0(".rslurm_", slr_job$jobname)
    missing_files <- setdiff(res_files, dir(path = tmpdir))
    if (length(missing_files) > 0) {
        missing_list <- paste(missing_files, collapse = ", ")
        warning(paste("The following files are missing:", missing_list))
    }
    res_files <- file.path(tmpdir, setdiff(res_files, missing_files))
    if (length(res_files) == 0) return(NA)
    
    slurm_out <- lapply(res_files, readRDS)
    slurm_out <- do.call(c, slurm_out)
    
    if (outtype == "table") {
        slurm_out <- as.data.frame(do.call(rbind, slurm_out))
    }
    slurm_out
}


#' Deletes temporary files associated with a SLURM job 
#'
#' This function deletes all temporary files associated with the specified SLURM
#' job, including files created by \code{\link{slurm_apply}} (parameters data, R
#' and Bash scripts, all starting with "slr####"), function output files
#' ("slr####_[node_id].out") as well as the console and error output files
#' (starting with "slurm-[job_id]").
#' 
#' @param slr_job A \code{slurm_job} object output by \code{\link{slurm_apply}}.
#' @examples 
#' \dontrun{
#' sjob <- slurm_apply(func, pars)
#' print_job_status(sjob) # Prints console/error output once job is completed.
#' func_result <- get_slurm_out(sjob, "table") # Loads output data into R.
#' cleanup_files(sjob)
#' }
#' @seealso \code{\link{slurm_apply}}, \code{\link{print_job_status}},
#'   \code{\link{get_slurm_out}}
#' @export
cleanup_files <- function(slr_job) {
    if (!(class(slr_job) == "slurm_job")) stop("input must be a slurm_job")
    tmpdir <- paste0(".rslurm_", slr_job$jobname)
    unlink(tmpdir, recursive = TRUE)
}
